# Menus
bindd = ALT, SPACE, Launch apps, exec, omarchy-launch-walker
bindd = ALT CTRL, E, Emoji picker, exec, omarchy-launch-walker -m symbols
bindd = ALT CTRL, C, Capture menu, exec, omarchy-menu capture
bindd = ALT CTRL, O, Toggle menu, exec, omarchy-menu toggle
bindd = SUPER ALT, SPACE, Omarchy menu, exec, omarchy-menu
bindd = ALT, ESCAPE, System menu, exec, omarchy-menu system
bindld = , XF86PowerOff, Power menu, exec, omarchy-menu system
bindd = ALT, K, Show key bindings, exec, omarchy-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = ALT SHIFT, SPACE, Toggle top bar, exec, omarchy-toggle-waybar
bindd = ALT CTRL, SPACE, Theme background menu, exec, omarchy-menu background
bindd = ALT SHIFT CTRL, SPACE, Theme menu, exec, omarchy-menu theme
bindd = ALT, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = ALT SHIFT, BACKSPACE, Toggle window gaps, exec, omarchy-hyprland-window-gaps-toggle
bindd = ALT CTRL, BACKSPACE, Toggle single-window square aspect, exec, omarchy-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = ALT, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = ALT SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = ALT CTRL, COMMA, Toggle silencing notifications, exec, omarchy-toggle-notification-silencing
bindd = ALT ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = ALT SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = ALT CTRL, I, Toggle locking on idle, exec, omarchy-toggle-idle
bindd = ALT CTRL, N, Toggle nightlight, exec, omarchy-toggle-nightlight

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, omarchy-brightness-display-apple -5000
bindd = CTRL, F2, Apple Display brightness up, exec, omarchy-brightness-display-apple +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, omarchy-brightness-display-apple +60000

# Captures
bindd = , PRINT, Screenshot, exec, omarchy-cmd-screenshot
bindd = ALT, PRINT, Screenrecording, exec, omarchy-menu screenrecord
bindd = ALT, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# File sharing
bindd = ALT CTRL, S, Share, exec, omarchy-menu share

# Waybar-less information
bindd = ALT CTRL ALT, T, Show time, exec, notify-send "    $(date +"%A %H:%M  —  %d %B W%V %Y")"
bindd = ALT CTRL ALT, B, Show battery remaining, exec, notify-send "$(omarchy-battery-status)"

# Control panels
bindd = ALT CTRL, A, Audio controls, exec, omarchy-launch-audio
bindd = ALT CTRL, B, Bluetooth controls, exec, omarchy-launch-bluetooth
bindd = ALT CTRL, W, Wifi controls, exec, omarchy-launch-wifi
bindd = ALT CTRL, T, Activity, exec, omarchy-launch-tui btop

# Dictation
bindd = ALT CTRL, X, Toggle dictation, exec, voxtype record toggle

# Zoom
bindd = ALT CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = ALT CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = ALT CTRL, L, Lock system, exec, omarchy-lock-screen
